# Generated by Django 4.1.3 on 2022-11-21 11:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='SY')),
                ('telegram', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='SY')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='SY')),
                ('land_line_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=7, region='SY')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_From', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_us', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sections.about')),
                ('contact_us', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sections.contactus')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.logo')),
                ('social_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.sociallinkmodel')),
                ('teaching', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sections.teaching')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
