# Generated by Django 4.1.5 on 2023-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_section_video_remove_sections_course_and_more'),
        ('account', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='enrolled_at',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
