# Generated by Django 4.1.5 on 2023-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customer_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
