# Generated by Django 4.1.5 on 2023-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_section_video_remove_sections_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtitles',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='_', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=6),
        ),
    ]
