# Generated by Django 4.1.5 on 2023-01-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer_tutor'),
        ('courses', '0004_rename_subtitles_video_subtitle_course_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number_of_enrollment',
            new_name='number_of_enrollments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='section',
            name='number',
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_enrollment', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.customer')),
            ],
        ),
    ]
