# Generated by Django 4.1.5 on 2023-01-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_number_of_enrollment_course_number_of_enrollments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.section'),
        ),
    ]
